"""Governance Proof Renderer.

Generates immutable proof artifacts from ledger traces.
"This document is a formattted projection of existing facts."
"""
from __future__ import annotations

import os
from typing import Any
from datetime import datetime


def generate_proof(result: dict[str, Any]) -> str:
    """Generate Markdown proof from scenario result."""
    thread_id = result.get("thread_id", "unknown")
    events = result.get("events", [])
    scenario = result.get("scenario_title", result.get("scenario", "unknown"))
    
    # 1. Extract Verdict Data from Events (Witness Logic)
    decision = "UNKNOWN"
    policy_id = "unknown"
    exec_status = "UNKNOWN"
    exec_error = None
    
    for e in events:
        kind = e.get("kind")
        payload = e.get("payload", {})
        
        if kind == "DECISION":
            decision = payload.get("decision", "UNKNOWN")
            policy_id = payload.get("policy_id", "unknown")
            
        elif kind == "EXECUTION":
            if "error" in payload:
                exec_status = "FAILED"
                err = payload.get("error", {})
                exec_error = err.get("code") or err.get("message") or "unknown"
            else:
                exec_status = "SUCCESS"
                exec_error = None

    # Icon Logic
    decision_icon = "✅" if decision == "ALLOW" else "🛑"
    exec_icon = "✅" if exec_status == "SUCCESS" else "❌"
    if exec_status == "UNKNOWN":
        exec_icon = "❓"

    # 2. Build Markdown
    timestamp = datetime.utcnow().isoformat() + "Z"
    
    md = f"""# GOVERNANCE PROOF

Thread ID: `{thread_id}`
Generated: `{timestamp}`
Scenario:  `{scenario}`

Source of Authority: **DBL-GATEWAY** (immutable event ledger)

---

## Verdict

### Decision
- **Authority:** DBL-GATEWAY
- **Result:** {decision_icon} {decision}
- **Policy ID:** `{policy_id}`

### Execution
- **Status:** {exec_icon} {exec_status}
"""

    if exec_error:
        md += f"- **Error Code:** `{exec_error}`\n"
        md += "- **Responsibility:** External Provider\n"
    elif exec_status == "SUCCESS":
        md += "- **Responsibility:** External Provider\n"
    
    md += """
---

## Ledger Evidence

The following events were recorded in order:

"""

    for i, e in enumerate(events):
        kind = e.get("kind", "?")
        turn_id = e.get("turn_id", "?")
        # Digest simulation (real gateway has digest, here we simulate or extract if available)
        # Gateway snapshot V2 usually has event_id or digest.
        digest = e.get("id", e.get("event_id", "sha256:???"))
        
        md += f"{i}. **{kind}**\n"
        md += f"   - turn_id: `{turn_id}`\n"
        md += f"   - digest: `{digest}`\n\n"

    md += """---

## Interpretation Boundary

This document does not interpret outcomes.

It proves:
- that a decision was made
- by whom it was made
- and what happened afterwards

Failures in execution do not invalidate governance correctness.

---

**Generated by:**
`dbl-domainrunner-governance-failure`
**Role:** Witness (non-normative)
"""
    return md


def save_proof(result: dict[str, Any]) -> str | None:
    """Generate and save proof to file."""
    try:
        content = generate_proof(result)
        thread_id = result.get("thread_id", "unknown")
        
        os.makedirs("proofs", exist_ok=True)
        filename = f"proofs/proof_{thread_id}.md"
        
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)
            
        return filename
    except Exception:
        return None
